export default [
  {
    index: 1,
    title: "导言",
    single: true,
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    page: import("../src/ppt/preface.vue"),
  },
  {
    index: 2,
    title: "1",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page1.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 3,
    title: "2",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page2.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 4,
    title: "3",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page3.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 5,
    title: "4",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page4.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 6,
    title: "5",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page5.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 7,
    title: "6",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page6.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 8,
    title: "7",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page7.vue"),
    right: import("../src/components/Material.vue"),
  },
  {
    index: 9,
    title: "8",
    firstEnter:true,
    enterMoment: 0,
    leaveMoment: 0,
    firstEvent: 0,
    left: import("../src/ppt/Page8.vue"),
    right: import("../src/components/Material.vue"),
  },

];
